# Site settings
name: Ben Levy
email: benlevy3.14@gmail.com
formspree_url: "https://formspree.io/f/mgeprkal"
keywords: "Software Developer, C#, Linq, SQL, Vue.js, Agile, X++, Dynamics AX"
skills: "Software Developer in Columbus, OH"
baseurl: ""

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/levy-ben/
  - title: github
    url: https://github.com/evilneb
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 03998b
  primary-rgb: "3, 153, 139"
  secondary: 015e55
  secondary-dark: 01332e
  section-tout: bfd9d6



# Build settings
markdown: kramdown
permalink: pretty
